database:
  host: localhost
  port: 3306
  name: dbname
  user: dbuser
  password: dbpassword

messages:
  prefix: "§c[Smokings] §f"
  noPermission: "§cDu hast keine Rechte!"
  notEnoughMoney: "§cNicht genug Geld!"
